### ISSUE TITLE
Setup installer should close once browser launches on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/omaha#3] opened 2018-07-18 16:30 UTC
Currently running BraveDevSetup.exe doesn't close the setup launcher even after browser is launched post setup. 

https://bravesoftware.slack.com/archives/CA5FPHWLF/p1531929868000151

Similar to Chrome setup, installer window should close once setup finishes installing and launches browser.

cc: @RyanJarv

**Comment by RyanJarv** [comment] 2018-07-18 23:05
@simonhong any idea why this dialog box would remain open?

**Comment by simonhong** [comment] 2018-07-19 00:03
Hmm, I assume there should be an option for closing it in `Action` property.
I tested `successaction` parameter(exitsilently) of `postinstall` action.
But, didn't work as I expected.
I think I don't know how to use it properly. Need to check related source code around it.
Can you assign this to me?

**Comment by mherrmann** [comment] 2021-04-07 17:09
Issue still reproduces with the current release version of Brave. A browser window opens _and_ behind it, the downloader/installer stays open:

![image](https://user-images.githubusercontent.com/1076393/113906661-c4782080-97d4-11eb-9408-08cd2b64a7bf.png)

**Comment by mherrmann** [comment] 2021-04-14 16:06
@simonhong I'd like to tackle this. You never found out more than what you wrote above, did you?

**Comment by mherrmann** [comment] 2021-04-14 16:52
I found out what causes this. In its response to the update request, the server responds `successsaction="exitsilently"`. Firstly, note the three "s" in `successsaction`. Second, looking at https://github.com/brave/omaha/blob/f1407b11524f110d87fdb7496e153724a9f8d9e4/omaha/common/xml_const.cc#L133, the client actually expects the attribute to be called `onsuccess`, not `successsaction`. I just verified this with a local Omaha client/server installation. So the fix will be to update the server implementation to respond `onsuccess` instead of `successsaction` and then to update CI pipelines to create a `postinstall` `Action` for new versions with the `onsuccess` (/`successsaction`) property set to `exitsilently`. I will begin by sending a PR for the server side.

**Comment by simonhong** [comment] 2021-04-14 23:28
@mherrmann I don't have more except above I mentioned :) and thanks for taking this!

**Comment by mherrmann** [comment] 2021-04-19 11:41
The server implementation was now updated to use the `onsuccess` field. Todo before the fix reaches all users:

- [x] Deploy the server fix to staging
- [x] Manually add a `postinstall` `Action` for the latest version on staging with `onsuccess` set to `exitsilently` via `/admin` or the REST API.
- [x] Test that a Windows online installer that fetches from staging works and no longer displays the "Installation complete" message. (This can also be achieved by setting the registry key `UpdateDev/url` to the staging server's `.../service/update2` URL. See [here](https://omaha-consulting.com/google-omaha-tutorial-chrome-updater).)
- [x] Extend the script that uploads Brave's new Windows versions to the update server so it also creates the `postinstall` action described above via the server's REST API.
- [x] Deploy to prod.

cc @mihaiplesa

**Comment by mihaiplesa** [comment] 2021-06-16 19:57
The server side has been deployed to production and tested manually but unfortunately does not close the installer after the browser is launched. Tested with both `launchsilently` and `launchsilentlyoncmd` and confirmed they appear in the update log on the client side (instead of `default`).

There is a pending Omaha client rebase at https://github.com/brave/omaha/pull/34 but it has conflicts so help would be appreciated @simonhong

**Comment by mherrmann** [comment] 2021-06-21 11:39
@mihaiplesa I would have expected `exitsilently`, not `launchsilently` or `launchsilentlyoncmd`. I also just tested with Brave stable's 1MB online installer and got:

```
<response ...>
    ...
    <actions>
        <action event="install"/>
        <action event="update"/>
    </actions>
    ...
</response>
```

Here, I would have expected an additional `<action event="postinstall" onsuccess="exitsilently"/>`.

**Comment by mihaiplesa** [comment] 2021-07-01 21:33
It does have `onsuccess` as you suggested but installer still not closes. Can wait till the rebase happens.

**Comment by mherrmann** [comment] 2021-07-02 15:29
Hm, so I don't see the `onsuccess` I described above in the server response from Brave stable:

![image](https://user-images.githubusercontent.com/1076393/124296599-6ef4ab00-db5a-11eb-9e21-4a63e21ae87d.png)

(As I wrote above, I would have expected an additional line `<action event="postinstall" onsuccess="exitsilently"/>` here.)

Do I understand correctly @mihaiplesa that in the update server admin, you do see a "postinstall" action with "exitsilently" as onsuccess? So in other words, do I understand correctly that the postinstall action is set in the admin (/REST API) for version 91.1.26.74? If yes, then me not getting that in the response would be a bug in the server implementation (or maybe a cache before it).

**Comment by mihaiplesa** [comment] 2021-07-02 15:31
You're correct but I tested then reverted hence you're not seeing it.

**Comment by mherrmann** [comment] 2021-07-02 15:35
I see. My curiosity would drive me to want to see it for myself too, but I'd also be happy to wait for the Omaha rebase if you like.

**Comment by mihaiplesa** [comment] 2021-07-02 15:37
Enabled again now on nightly so you should see it.

**Comment by mherrmann** [comment] 2021-07-02 15:43
Thank you. It's not what I expected:
![image](https://user-images.githubusercontent.com/1076393/124298680-d3186e80-db5c-11eb-896b-f70f15246f69.png)
It's subtle but I think `exitsilently` must be set on a `postinstall` action. Here, it is set on the `install` and `update` actions. I think you would need to add another, separate action of type `postinstall` with `exitsilently` set. It does not need to be set on the other actions. Just on `postinstall`.

**Comment by mihaiplesa** [comment] 2021-07-02 15:45
Great point, have added, please retry.

**Comment by mherrmann** [comment] 2021-07-02 15:58
Thanks. It's not working and I suspect it is because there are arguments to the `postinstall` action:

![image](https://user-images.githubusercontent.com/1076393/124300397-d280d780-db5e-11eb-829c-c5ee6a506d67.png)

(At least that's my reading of https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/omaha/goopdate/install_manager.cc#L348 and https://github.com/brave/omaha/blob/aa5d8f956d6b4fc929d835995b25df159af6dcf9/omaha/goopdate/installer_wrapper.cc#L601)

Can I ask you to remove the `--chrome-sxs` argument for the `postinstall` action?

**Comment by mihaiplesa** [comment] 2021-07-02 16:00
Sure, done.

**Comment by mherrmann** [comment] 2021-07-02 16:12
There are two values for `postinstall` - `exitsilently` and `exitsilentlyonlaunchcmd`. I thought we need the former, but it seems that Chromium puts Omaha into a mode where it actually requires the latter.

Can you change `exitsilently` to `exitsilentlyonlaunchcmd` please?

(Reason for my suspicion is that I see the following in the log:

```[InstallApp returned][0x0][{C6CB981E-DB30-4876-8639-109F8933582C}][type:1][code: 0][]["C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe" --from-installer]```

The last part `...\brave.exe --from-installer` seems to come from Chromium and is the value of a field `result.post_install_launch_command_line`. [`installer_wrapper.cc`](https://github.com/brave/omaha/blob/main/omaha/goopdate/installer_wrapper.cc#L601-L603) seems to set the post install action to "launch command" when this field is non-empty:

```
else if (!result.post_install_launch_command_line.IsEmpty()) {
    result.post_install_action = POST_INSTALL_ACTION_LAUNCH_COMMAND;
}
```

)

**Comment by mihaiplesa** [comment] 2021-07-02 16:18
Have updated.

**Comment by mherrmann** [comment] 2021-07-02 16:20
Works for me now :)

I believe it should also work if we remove `exitsilently` from the other two actions:

![image](https://user-images.githubusercontent.com/1076393/124303015-38229300-db62-11eb-8a84-bb7e9a436395.png)

If you wanted, you could remove them and I could test this to verify.

**Comment by mihaiplesa** [comment] 2021-07-02 16:22
Have removed them now. If this works then I will update the pipelines to populate the new field.

**Comment by mherrmann** [comment] 2021-07-02 16:24
Still works for me :-)

**Comment by mherrmann** [comment] 2021-07-02 16:24
My log, for reference:

        <actions>
          <action event="install" arguments="--chrome-sxs" onsuccess="default"/>
          <action event="update" arguments="--chrome-sxs" onsuccess="default"/>
          <action event="postinstall" onsuccess="exitsilentlyonlaunchcmd"/>
        </actions>

**Comment by mihaiplesa** [comment] 2021-07-02 16:25
What if we have onsuccess on default for postinstall? I've set that now.

**Comment by mherrmann** [comment] 2021-07-02 16:28
Then the installer window again remains for me. Log:

![image](https://user-images.githubusercontent.com/1076393/124303836-34434080-db63-11eb-8017-3c1db626ed68.png)

So I think we really do need to set it to `exitsilentlyonlaunchcmd`.

**Comment by mihaiplesa** [comment] 2021-07-02 16:30
Ok, I think we're good for now. Thanks!

**Comment by mherrmann** [comment] 2021-07-02 16:31
Sure! I'm happy it seems to be working :-)

**Closed as completed** 2021-07-02 19:11 UTC
